name: Android CI (Build Debug APK & Release AAB)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle build (Debug APK)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Gradle build (Release AAB)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:bundleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metroalarm-builds
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/release/*.aab
